# Change these first
owner: doodad-labs
repo: uptime-monitor

sites:
  - name: Main Site
    url: https://doodadlabs.org
    type: globalping
  - name: Authentication Service
    url: https://auth.doodadlabs.org/health
    type: globalping
  - name: Ingest API
    url: https://ingest.doodadlabs.org/health
    type: globalping
assignees:
  - NotReeceHarris
status-website:
  cname: status.doodadlabs.org
  logoUrl: https://doodadlabs.org/favicon.svg
  name: Doodadlabs
  introTitle: "**DoodadLabs Status**"
  introMessage: "Track the status of DoodadLab systems. While we operate on a global infrastructure designed for 99% uptime, occasional disruptions may occur."

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
